/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-05-28 09:31:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.my_0020pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class singleprodlayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/H:/eclipse%20files/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frontend/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098691290000L));
    _jspx_dependants.put("jar:file:/H:/eclipse%20files/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/frontend/WEB-INF/lib/spring-webmvc-5.0.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1516679068000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.3.RELEASE.jar", Long.valueOf(1518366906244L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1522659439926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title </title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("               <div class=\"col-xs-4 item-photo\">\r\n");
      out.write("                    <img style=\"max-width:100%;\" src=\"https://ak1.ostkcdn.com/images/products/8818677/Samsung-Galaxy-S4-I337-16GB-AT-T-Unlocked-GSM-Android-Cell-Phone-85e3430e-6981-4252-a984-245862302c78_600.jpg\" />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-xs-5\" style=\"border:0px solid gray\">\r\n");
      out.write("                    <<h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productModelAgent.getProductName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>    \r\n");
      out.write("\t\t\t\t\t ");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                    \r\n");
      out.write("                    <h3 style=\"margin-top:0px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productModelAgent.getProductPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("        \r\n");
      out.write("                    <div class=\"section\">\r\n");
      out.write("                        <h6 class=\"title-attr\" style=\"margin-top:15px;\" ><small>Limited offer!!</small></h6>                    \r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"attr\" style=\"width:25px;background:#5a5a5a;\"></div>\r\n");
      out.write("                            <div class=\"attr\" style=\"width:25px;background:white;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"section\" style=\"padding-bottom:5px;\"> \r\n");
      out.write("                        <div>\r\n");
      out.write("          <!--                   <div class=\"attr2\">16 GB</div>\r\n");
      out.write("                            <div class=\"attr2\">32 GB</div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>   \r\n");
      out.write("                    <div class=\"section\" style=\"padding-bottom:20px;\">\r\n");
      out.write("                        <h6 class=\"title-attr\"><small>Quantity</small></h6>                    \r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"btn-minus\"><span class=\"glyphicon glyphicon-minus\"></span></div>\r\n");
      out.write("                            <input value=\"1\" />\r\n");
      out.write("                            <div class=\"btn-plus\"><span class=\"glyphicon glyphicon-plus\"></span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>                \r\n");
      out.write("        \r\n");
      out.write("                     <div class=\"section\" style=\"padding-bottom:20px;\">\r\n");
      out.write("                        <button class=\"btn btn-success\"><span style=\"margin-right:20px\" class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span> BUY NOW</button>\r\n");
      out.write("                        <h6><a href=\"#\"><span class=\"glyphicon glyphicon-heart-empty\" style=\"cursor:pointer;\"></span> Add  to cart</a></h6>\r\n");
      out.write("                    </div>                                        \r\n");
      out.write("                </div>                              \r\n");
      out.write("        \r\n");
      out.write("                <div class=\"col-xs-9\">\r\n");
      out.write("                    <ul class=\"menu-items\">\r\n");
      out.write("<!--                         <li class=\"active\">Detalle del producto</li>\r\n");
      out.write("                        <li>Garantía</li>\r\n");
      out.write("                        <li>Vendedor</li>\r\n");
      out.write("                        <li>Envío</li>\r\n");
      out.write(" -->                    </ul>\r\n");
      out.write("                    <div style=\"width:100%;border-top:1px solid silver\">\r\n");
      out.write("             ");
      out.write("                            <!-- <small>\r\n");
      out.write("                            Stay connected either on the phone or the Web with the Galaxy S4 I337 from Samsung. With 16 GB of memory and a 4G connection, this phone stores precious photos and video and lets you upload them to a cloud or social network at blinding-fast speed. With a 17-hour operating life from one charge, this phone allows you keep in touch even on the go. \r\n");
      out.write("        \r\n");
      out.write("                            With its built-in photo editor, the Galaxy S4 allows you to edit photos with the touch of a finger, eliminating extraneous background items. Usable with most carriers, this smartphone is the perfect companion for work or entertainment.\r\n");
      out.write("                            </small>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <small>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>Super AMOLED capacitive touchscreen display with 16M colors</li>\r\n");
      out.write("                                <li>Available on GSM, AT T, T-Mobile and other carriers</li>\r\n");
      out.write("                                <li>Compatible with GSM 850 / 900 / 1800; HSDPA 850 / 1900 / 2100 LTE; 700 MHz Class 17 / 1700 / 2100 networks</li>\r\n");
      out.write("                                <li>MicroUSB and USB connectivity</li>\r\n");
      out.write("                                <li>Interfaces with Wi-Fi 802.11 a/b/g/n/ac, dual band and Bluetooth</li>\r\n");
      out.write("                                <li>Wi-Fi hotspot to keep other devices online when a connection is not available</li>\r\n");
      out.write("                                <li>SMS, MMS, email, Push Mail, IM and RSS messaging</li>\r\n");
      out.write("                                <li>Front-facing camera features autofocus, an LED flash, dual video call capability and a sharp 4128 x 3096 pixel picture</li>\r\n");
      out.write("                                <li>Features 16 GB memory and 2 GB RAM</li>\r\n");
      out.write("                                <li>Upgradeable Jelly Bean v4.2.2 to Jelly Bean v4.3 Android OS</li>\r\n");
      out.write("                                <li>17 hours of talk time, 350 hours standby time on one charge</li>\r\n");
      out.write("                                <li>Available in white or black</li>\r\n");
      out.write("                                <li>Model I337</li>\r\n");
      out.write("                                <li>Package includes phone, charger, battery and user manual</li>\r\n");
      out.write("                                <li>Phone is 5.38 inches high x 2.75 inches wide x 0.13 inches deep and weighs a mere 4.59 oz </li>\r\n");
      out.write("                            </ul>  \r\n");
      out.write("                        </small>\r\n");
      out.write("         -->\r\n");
      out.write("\t\t\t\t\t<!-- </p>  -->        \r\n");
      out.write("                     </div>\r\n");
      out.write("                </div>\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
